/*
 * Created on 24 Apr 2014 ( Time 16:20:58 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.researchermall.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "td_invitation"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="td_invitation"/* , catalog="community"*/)
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="InvitationEntity.countAll", query="SELECT COUNT(x) FROM InvitationEntity x" )
} )
public class InvitationEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="CommunityId", nullable=false)
    private Integer    communityid  ;

    @Column(name="Invitor", nullable=false)
    private Integer    invitor      ;

    @Column(name="Invitee", nullable=false)
    private Integer    invitee      ;

    @Column(name="Result", nullable=false)
    private Boolean    result       ;

    @Column(name="InvitationCode", nullable=false, length=50)
    private String     invitationcode ;

    @Column(name="CreateBy", nullable=false)
    private Integer    createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", nullable=false, insertable=false)
    private Date       createdate   ;

    @Column(name="UpdateBy")
    private Integer    updateby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdateDate")
    private Date       updatedate   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public InvitationEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : CommunityId ( INT ) 
    public void setCommunityid( Integer communityid ) {
        this.communityid = communityid;
    }
    public Integer getCommunityid() {
        return this.communityid;
    }

    //--- DATABASE MAPPING : Invitor ( INT ) 
    public void setInvitor( Integer invitor ) {
        this.invitor = invitor;
    }
    public Integer getInvitor() {
        return this.invitor;
    }

    //--- DATABASE MAPPING : Invitee ( INT ) 
    public void setInvitee( Integer invitee ) {
        this.invitee = invitee;
    }
    public Integer getInvitee() {
        return this.invitee;
    }

    //--- DATABASE MAPPING : Result ( BIT ) 
    public void setResult( Boolean result ) {
        this.result = result;
    }
    public Boolean getResult() {
        return this.result;
    }

    //--- DATABASE MAPPING : InvitationCode ( VARCHAR ) 
    public void setInvitationcode( String invitationcode ) {
        this.invitationcode = invitationcode;
    }
    public String getInvitationcode() {
        return this.invitationcode;
    }

    //--- DATABASE MAPPING : CreateBy ( INT ) 
    public void setCreateby( Integer createby ) {
        this.createby = createby;
    }
    public Integer getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : CreateDate ( TIMESTAMP ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : UpdateBy ( INT ) 
    public void setUpdateby( Integer updateby ) {
        this.updateby = updateby;
    }
    public Integer getUpdateby() {
        return this.updateby;
    }

    //--- DATABASE MAPPING : UpdateDate ( DATETIME ) 
    public void setUpdatedate( Date updatedate ) {
        this.updatedate = updatedate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(communityid);
        sb.append("|");
        sb.append(invitor);
        sb.append("|");
        sb.append(invitee);
        sb.append("|");
        sb.append(result);
        sb.append("|");
        sb.append(invitationcode);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(updateby);
        sb.append("|");
        sb.append(updatedate);
        return sb.toString(); 
    } 

}
