/*
 * Created on 1 May 2014 ( Time 10:13:01 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.researchermall.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "td_algorithm_review"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="td_algorithm_review", catalog="community" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TdAlgorithmReviewEntity.countAll", query="SELECT COUNT(x) FROM TdAlgorithmReviewEntity x" )
} )
public class TdAlgorithmReviewEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="AlgorId", nullable=false)
    private Integer    algorid      ;

    @Column(name="UserId", nullable=false)
    private Integer    userid       ;

    @Column(name="Comments", length=250)
    private String     comments     ;

    @Lob
    @Column(name="Picture")
    private byte[]     picture      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ReviewDate")
    private Date       reviewdate   ;

    @Column(name="Status", nullable=false, length=2)
    private String     status       ;

    @Column(name="CreateBy", nullable=false)
    private Integer    createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", nullable=false)
    private Date       createdate   ;

    @Column(name="UpdateBy")
    private Integer    updateby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdateDate")
    private Date       updatedate   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TdAlgorithmReviewEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : AlgorId ( INT ) 
    public void setAlgorid( Integer algorid ) {
        this.algorid = algorid;
    }
    public Integer getAlgorid() {
        return this.algorid;
    }

    //--- DATABASE MAPPING : UserId ( INT ) 
    public void setUserid( Integer userid ) {
        this.userid = userid;
    }
    public Integer getUserid() {
        return this.userid;
    }

    //--- DATABASE MAPPING : Comments ( VARCHAR ) 
    public void setComments( String comments ) {
        this.comments = comments;
    }
    public String getComments() {
        return this.comments;
    }

    //--- DATABASE MAPPING : Picture ( BLOB ) 
    public void setPicture( byte[] picture ) {
        this.picture = picture;
    }
    public byte[] getPicture() {
        return this.picture;
    }

    //--- DATABASE MAPPING : ReviewDate ( DATETIME ) 
    public void setReviewdate( Date reviewdate ) {
        this.reviewdate = reviewdate;
    }
    public Date getReviewdate() {
        return this.reviewdate;
    }

    //--- DATABASE MAPPING : Status ( CHAR ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : CreateBy ( INT ) 
    public void setCreateby( Integer createby ) {
        this.createby = createby;
    }
    public Integer getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : CreateDate ( TIMESTAMP ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : UpdateBy ( INT ) 
    public void setUpdateby( Integer updateby ) {
        this.updateby = updateby;
    }
    public Integer getUpdateby() {
        return this.updateby;
    }

    //--- DATABASE MAPPING : UpdateDate ( DATETIME ) 
    public void setUpdatedate( Date updatedate ) {
        this.updatedate = updatedate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(algorid);
        sb.append("|");
        sb.append(userid);
        sb.append("|");
        sb.append(comments);
        // attribute 'picture' not usable (type = byte[])
        sb.append("|");
        sb.append(reviewdate);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(updateby);
        sb.append("|");
        sb.append(updatedate);
        return sb.toString(); 
    } 

}
