/*
 * Created on 1 May 2014 ( Time 10:13:07 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.researchermall.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "td_algorithm_status_history"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="td_algorithm_status_history", catalog="community" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TdAlgorithmStatusHistoryEntity.countAll", query="SELECT COUNT(x) FROM TdAlgorithmStatusHistoryEntity x" )
} )
public class TdAlgorithmStatusHistoryEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="AlgorId", nullable=false)
    private Integer    algorid      ;

    @Column(name="OldStatus", nullable=false, length=2)
    private String     oldstatus    ;

    @Column(name="NewStatus", nullable=false, length=2)
    private String     newstatus    ;

    @Column(name="MustNotified", nullable=false)
    private Boolean    mustnotified ;

    @Column(name="CreateBy", nullable=false)
    private Integer    createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", nullable=false)
    private Date       createdate   ;

    @Column(name="UpdateBy")
    private Integer    updateby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdateDate")
    private Date       updatedate   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TdAlgorithmStatusHistoryEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : AlgorId ( INT ) 
    public void setAlgorid( Integer algorid ) {
        this.algorid = algorid;
    }
    public Integer getAlgorid() {
        return this.algorid;
    }

    //--- DATABASE MAPPING : OldStatus ( CHAR ) 
    public void setOldstatus( String oldstatus ) {
        this.oldstatus = oldstatus;
    }
    public String getOldstatus() {
        return this.oldstatus;
    }

    //--- DATABASE MAPPING : NewStatus ( CHAR ) 
    public void setNewstatus( String newstatus ) {
        this.newstatus = newstatus;
    }
    public String getNewstatus() {
        return this.newstatus;
    }

    //--- DATABASE MAPPING : MustNotified ( BIT ) 
    public void setMustnotified( Boolean mustnotified ) {
        this.mustnotified = mustnotified;
    }
    public Boolean getMustnotified() {
        return this.mustnotified;
    }

    //--- DATABASE MAPPING : CreateBy ( INT ) 
    public void setCreateby( Integer createby ) {
        this.createby = createby;
    }
    public Integer getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : CreateDate ( TIMESTAMP ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : UpdateBy ( INT ) 
    public void setUpdateby( Integer updateby ) {
        this.updateby = updateby;
    }
    public Integer getUpdateby() {
        return this.updateby;
    }

    //--- DATABASE MAPPING : UpdateDate ( DATETIME ) 
    public void setUpdatedate( Date updatedate ) {
        this.updatedate = updatedate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(algorid);
        sb.append("|");
        sb.append(oldstatus);
        sb.append("|");
        sb.append(newstatus);
        sb.append("|");
        sb.append(mustnotified);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(updateby);
        sb.append("|");
        sb.append(updatedate);
        return sb.toString(); 
    } 

}
