/*
 * Created on 1 May 2014 ( Time 10:13:41 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.researchermall.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "td_role"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="td_role", catalog="community" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TdRoleEntity.countAll", query="SELECT COUNT(x) FROM TdRoleEntity x" )
} )
public class TdRoleEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="RoleName", nullable=false, length=35)
    private String     rolename     ;

    @Column(name="Desc", length=200)
    private String     desc         ;

    @Column(name="AllowLogin", nullable=false)
    private Boolean    allowlogin   ;

    @Column(name="AllowDownload", nullable=false)
    private Boolean    allowdownload ;

    @Column(name="AllowJoin", nullable=false)
    private Boolean    allowjoin    ;

    @Column(name="AllowCreateCommunity", nullable=false)
    private Boolean    allowcreatecommunity ;

    @Column(name="AllowSendMessage", nullable=false)
    private Boolean    allowsendmessage ;

    @Column(name="CreateBy", nullable=false)
    private Integer    createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", nullable=false)
    private Date       createdate   ;

    @Column(name="UpdateBy")
    private Integer    updateby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdateDate")
    private Date       updatedate   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TdRoleEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : RoleName ( VARCHAR ) 
    public void setRolename( String rolename ) {
        this.rolename = rolename;
    }
    public String getRolename() {
        return this.rolename;
    }

    //--- DATABASE MAPPING : Desc ( VARCHAR ) 
    public void setDesc( String desc ) {
        this.desc = desc;
    }
    public String getDesc() {
        return this.desc;
    }

    //--- DATABASE MAPPING : AllowLogin ( BIT ) 
    public void setAllowlogin( Boolean allowlogin ) {
        this.allowlogin = allowlogin;
    }
    public Boolean getAllowlogin() {
        return this.allowlogin;
    }

    //--- DATABASE MAPPING : AllowDownload ( BIT ) 
    public void setAllowdownload( Boolean allowdownload ) {
        this.allowdownload = allowdownload;
    }
    public Boolean getAllowdownload() {
        return this.allowdownload;
    }

    //--- DATABASE MAPPING : AllowJoin ( BIT ) 
    public void setAllowjoin( Boolean allowjoin ) {
        this.allowjoin = allowjoin;
    }
    public Boolean getAllowjoin() {
        return this.allowjoin;
    }

    //--- DATABASE MAPPING : AllowCreateCommunity ( BIT ) 
    public void setAllowcreatecommunity( Boolean allowcreatecommunity ) {
        this.allowcreatecommunity = allowcreatecommunity;
    }
    public Boolean getAllowcreatecommunity() {
        return this.allowcreatecommunity;
    }

    //--- DATABASE MAPPING : AllowSendMessage ( BIT ) 
    public void setAllowsendmessage( Boolean allowsendmessage ) {
        this.allowsendmessage = allowsendmessage;
    }
    public Boolean getAllowsendmessage() {
        return this.allowsendmessage;
    }

    //--- DATABASE MAPPING : CreateBy ( INT ) 
    public void setCreateby( Integer createby ) {
        this.createby = createby;
    }
    public Integer getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : CreateDate ( TIMESTAMP ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : UpdateBy ( INT ) 
    public void setUpdateby( Integer updateby ) {
        this.updateby = updateby;
    }
    public Integer getUpdateby() {
        return this.updateby;
    }

    //--- DATABASE MAPPING : UpdateDate ( DATETIME ) 
    public void setUpdatedate( Date updatedate ) {
        this.updatedate = updatedate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(rolename);
        sb.append("|");
        sb.append(desc);
        sb.append("|");
        sb.append(allowlogin);
        sb.append("|");
        sb.append(allowdownload);
        sb.append("|");
        sb.append(allowjoin);
        sb.append("|");
        sb.append(allowcreatecommunity);
        sb.append("|");
        sb.append(allowsendmessage);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(updateby);
        sb.append("|");
        sb.append(updatedate);
        return sb.toString(); 
    } 

}
