/*
 * Created on 24 Apr 2014 ( Time 16:21:05 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.researchermall.bean;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "td_member"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="td_member"/* , catalog="community"*/)
@IdClass(MemberId.class)
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="MemberEntity.countAll", query="SELECT COUNT(x) FROM MemberEntity x" )
} )
public class MemberEntity{

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Id
    private Integer    communityid  ;

    @Id
    private Integer    userid       ;

    @Column(name="Role", nullable=false, length=50)
    private String     role         ;

    @Column(name="Confirmed", nullable=false)
    private Boolean    confirmed    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ExpireDate", nullable=false)
    private Date       expiredate   ;

    @Column(name="CreateBy", nullable=false)
    private Integer    createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate")
    private Date       createdate   ;

    @Column(name="UpdateBy")
    private Integer    updateby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdateDate")
    private Date       updatedate   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name = "userid", updatable = false, insertable = false, referencedColumnName = "id")
    private UserEntity user;
    
    @ManyToOne
    @JoinColumn(name = "communityid", updatable = false, insertable = false, referencedColumnName = "id")
    private CommunityEntity community;
    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MemberEntity() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : CommunityId ( INT ) 
    public void setCommunityid( Integer communityid ) {
        this.communityid = communityid;
    }
    public Integer getCommunityid() {
        return this.communityid;
    }

    //--- DATABASE MAPPING : UserId ( INT ) 
    public void setUserid( Integer userid ) {
        this.userid = userid;
    }
    public Integer getUserid() {
        return this.userid;
    }

    //--- DATABASE MAPPING : Role ( VARCHAR ) 
    public void setRole( String role ) {
        this.role = role;
    }
    public String getRole() {
        return this.role;
    }

    //--- DATABASE MAPPING : Confirmed ( BIT ) 
    public void setConfirmed( Boolean confirmed ) {
        this.confirmed = confirmed;
    }
    public Boolean getConfirmed() {
        return this.confirmed;
    }

    //--- DATABASE MAPPING : ExpireDate ( DATETIME ) 
    public void setExpiredate( Date expiredate ) {
        this.expiredate = expiredate;
    }
    public Date getExpiredate() {
        return this.expiredate;
    }

    //--- DATABASE MAPPING : CreateBy ( INT ) 
    public void setCreateby( Integer createby ) {
        this.createby = createby;
    }
    public Integer getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : CreateDate ( TIMESTAMP ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : UpdateBy ( INT ) 
    public void setUpdateby( Integer updateby ) {
        this.updateby = updateby;
    }
    public Integer getUpdateby() {
        return this.updateby;
    }

    //--- DATABASE MAPPING : UpdateDate ( DATETIME ) 
    public void setUpdatedate( Date updatedate ) {
        this.updatedate = updatedate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(communityid);
        sb.append("|");
        sb.append(userid);
        sb.append("|");
        sb.append(role);
        sb.append("|");
        sb.append(confirmed);
        sb.append("|");
        sb.append(expiredate);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(updateby);
        sb.append("|");
        sb.append(updatedate);
        return sb.toString(); 
    } 

}
